import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '@/widgets/themeProvider'
import LayoutWrapper from '@/widgets/layout/LayoutWrapper'
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/favicon.png" />
      </head>
      <body className="bg-background dark:bg-foreground">
        <ThemeProvider>
          <main className="max-w-3xl mx-auto my-14 px-4 font-self">
            <LayoutWrapper>{children}</LayoutWrapper>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}